'use client';

import {
  logo,
  backend,
  creator,
  mobile,
  web,
  github,
  menu,
  close,
  algolia,
  android,
  angular,
  aws,
  bootstrap,
  c,
  circleci,
  css,
  cypressjs,
  docker,
  echarts,
  electrode_native,
  expressjs,
  figma,
  flask,
  fusejs,
  gcp,
  git,
  githubTech,
  go,
  html,
  html_svg,
  java,
  javascript,
  jetbrains,
  jinja,
  gitlab,
  json,
  jwt,
  kotlin,
  laravel,
  mongodb,
  mongoose,
  mui,
  mysql,
  nextjs,
  nodejs,
  oracle_db,
  php,
  pl_sql,
  postgresql,
  preloader,
  python,
  rabbitmq,
  react,
  reactjs,
  redis,
  redux,
  reduxSaga,
  saml,
  sql_server,
  sqla,
  sso,
  swift,
  tailwind,
  terraform,
  threejs,
  typescript,
  vscode,
  xcode,
  paradigm_logo,
  datachat_logo,
  the_nine_logo,
  carlin_fit_llc_logo,
  infosys_logo,
  tracker_1,
  tracker_2,
  tracker_3,
  meals_1,
  meals_2,
  meals_3,
  blogs_1,
  blogs_2,
  blogs_3,
  tictactoe,
  target_sum,
  food_app,
  samantha_carlin,
  shreya_nayak,
  admin,
  singup,
  user_dashboard,
  registration_appointment,
} from '../../public/assets';

export const navLinks = [
  {
    id: 'about',
    title: 'About',
  },
  {
    id: 'work',
    title: 'Work',
  },
  {
    id: 'projects',
    title: 'Projects',
  },
  {
    id: 'contact',
    title: 'Contact',
  },
];

const services = [
  {
    title: 'Software Engineer',
    icon: web,
  },
  {
    title: 'Full Stack Engineer',
    icon: mobile,
  },
  {
    title: 'Mobile Developer',
    icon: backend,
  },
  {
    title: 'AI Engineer',
    icon: creator,
  },
];

const technologies = [
  {
    name: 'Python',
    icon: python,
  },
  {
    name: 'Flask',
    icon: flask,
  },
  {
    name: 'JavaScript',
    icon: javascript,
  },
  {
    name: 'MongoDB',
    icon: mongodb,
  },
  {
    name: 'SQLAlchemy',
    icon: sqla,
  },
  {
    name: 'Go',
    icon: go,
  },
  {
    name: 'MUI',
    icon: mui,
  },
  {
    name: 'Jinja',
    icon: jinja,
  },
  {
    name: 'Docker',
    icon: docker,
  },
  {
    name: 'SQL Server',
    icon: sql_server,
  },
  {
    name: 'Oracle DB',
    icon: oracle_db,
  },
  {
    name: 'PL/SQL',
    icon: pl_sql,
  },
  {
    name: 'Node JS',
    icon: nodejs,
  },
  {
    name: 'GitHub',
    icon: githubTech,
  },
  {
    name: 'HTML 5',
    icon: html,
  },
  {
    name: 'CSS 3',
    icon: css,
  },
  {
    name: 'Bootstrap',
    icon: bootstrap,
  },
  {
    name: 'VSCode',
    icon: vscode,
  },
  {
    name: 'JetBrains',
    icon: jetbrains,
  },
  {
    name: 'PostgreSQL',
    icon: postgresql,
  },
  {
    name: 'AWS',
    icon: aws,
  },
  {
    name: 'MySQL',
    icon: mysql,
  },
  {
    name: 'React JS',
    icon: reactjs,
  },
  {
    name: 'Kotlin',
    icon: kotlin,
  },
  {
    name: 'Java',
    icon: java,
  },
  {
    name: 'Xcode',
    icon: xcode,
  },
  {
    name: 'Swift',
    icon: swift,
  },
  {
    name: 'C',
    icon: c,
  },
  {
    name: 'JWT',
    icon: jwt,
  },
  {
    name: 'PHP',
    icon: php,
  },
  {
    name: 'Laravel',
    icon: laravel,
  },
  {
    name: 'Next.js',
    icon: nextjs,
  },
  {
    name: 'ExpressJS',
    icon: expressjs,
  },
  {
    name: 'CypressJS',
    icon: cypressjs,
  },
  {
    name: 'GitLab',
    icon: gitlab,
  },
  {
    name: 'Git',
    icon: git,
  },
  {
    name: 'FuseJS',
    icon: fusejs,
  },
  {
    name: 'ECharts',
    icon: echarts,
  },
  {
    name: 'Algolia',
    icon: algolia,
  },
  {
    name: 'CircleCI',
    icon: circleci,
  },
  {
    name: 'RabbitMQ',
    icon: rabbitmq,
  },
  {
    name: 'Electrode Native',
    icon: electrode_native,
  },
  {
    name: 'GCP',
    icon: gcp,
  },
  {
    name: 'SSO',
    icon: sso,
  },
  {
    name: 'SAML',
    icon: saml,
  },
  {
    name: 'Tailwind CSS',
    icon: tailwind,
  },
  {
    name: 'Terraform',
    icon: terraform,
  },
  {
    name: 'TypeScript',
    icon: typescript,
  },
  {
    name: 'Redis',
    icon: redis,
  },
  {
    name: 'Redux',
    icon: redux,
  },
  {
    name: 'Redux Saga',
    icon: reduxSaga,
  },
  {
    name: 'Mongoose',
    icon: mongoose,
  },
  {
    name: 'JSON',
    icon: json,
  },
  {
    name: 'Android',
    icon: android,
  },
  {
    name: 'Figma',
    icon: figma,
  },
];

const experiences = [
  {
    title: 'Senior Full Stack Engineer',
    company_name: 'Paradigm Healthcare Services',
    company_link: 'https://paradigm-healthcare.com/',
    icon: paradigm_logo,
    iconBg: '#F7F7F7',
    date: 'February 2023 - Present',
    points: [
      'Scaled a **Medicaid reimbursement platform** to support **3M+ student records** by modernizing backend architecture and aligning data models with evolving compliance standards across California school districts.',
      'Unified fragmented service layers into a centralized **Flask + SQLAlchemy API gateway**, enabling seamless third-party integrations and improving scalability with **JWT authentication**, **rate limiting**, and **Swagger documentation**.',
      'Accelerated internal debugging and API tracing by embedding an **offline, HIPAA-compliant AI assistant** using **LangChain**, **FAISS**, and local **LLMs (Mistral, Code Llama)** for natural language code search.',
      'Delivered a **zero-touch PDF generation pipeline** producing **10K+ immunization cards/day** using **Redis**, **SQLAlchemy**, and Python PDF tooling libraries (**PyPDF2**, **pdfrw**).',
      'Replaced biweekly deploys with **same-day, zero-downtime releases** by implementing **blue-green CI/CD workflows** using **Jenkins** and **AWS CodePipeline**.',
      'Reduced **operational costs by 40%** by implementing a **serverless notification system** with **AWS Lambda**, processing **1,000+ events/second** for real-time healthcare alerts.',
      'Automated **real-time NPI validation** using a containerized **Selenium pipeline**, cutting manual QA effort by **80%** and preventing credential issues from reaching production.',
      'Improved **API latency** by building **New Relic dashboards** that surfaced slow queries and bottlenecks without requiring deep infrastructure changes.',
      'Built **reporting pipelines** in collaboration with Ops, Finance, and Product teams to identify reimbursement gaps, resulting in **$1M+ in Medicaid recovery** and improved district budget planning.',
    ],
    tech_stack: [
      'JavaScript',
      'TypeScript',
      'Flask',
      'Flask-Mail',
      'Jinja2',
      'WTForms',
      'SQLAlchemy',
      'Python',
      'JavaScript',
      'jQuery',
      'HTML',
      'CSS',
      'Bootstrap',
      'Docker',
      'Datatables.js',
      'Chart.js',
      'XlsxWriter',
      'React.js',
      'REST APIs',
      'JSON',
      'SQL',
      'PL/SQL',
      'Oracle DB',
      'Redis',
      'AWS (EC2, Lambda, S3)',
      'CI/CD (Jenkins, AWS CodePipeline)',
      'Terraform',
      'New Relic',
      'Selenium',
      'Jira',
      'Agile',
      'OOP',
      'LangChain',
      'FAISS',
      'Mistral',
      'Code Llama',
      'pdfrw',
      'GitLab',
    ],
  },
  {
    title: 'Senior Software Engineer',
    company_name: 'DataChat Inc.',
    company_link: 'https://datachat.ai/',
    icon: datachat_logo,
    iconBg: '#F7F7F7',
    date: 'July 2021 - January 2023',
    points: [
      'Streamlined **data exploration for enterprise users** by building a full-stack analytics platform with **React.js**, **Go**, **Python**, and **SQLAlchemy**, enabling **natural language query-to-visualization workflows** that eliminated manual chart construction.',
      'Eliminated **database integration bottlenecks** by building **test-before-connect architecture** in **Flask** and **Material-UI**, unlocking real-time visualization across **10+ cloud data sources**.',
      'Improved **request throughput and system reliability** for multi-tenant users by migrating to a **microservices architecture** behind **NGINX**, tuning **caching** and load strategies to eliminate bottlenecks.',
      'Improved usability of **natural language analytics** by building **30+ domain-aware commands** in the **Python-based NLP engine**, reducing query friction and enabling accurate, auto-completed prompts.',
      'Transformed **isolated dashboards into collaborative workspaces** by shipping **25+ features** including **Algolia-based fuzzy search**, **cross-org chart sharing**, and **advanced filtering**.',
      'Launched a **revenue-generating SaaS version of DataChat** by integrating **Stripe billing**, **Google SSO**, and **tiered subscription orchestration**, transforming it from an internal tool into a scalable commercial product.',
      'Reduced **infrastructure setup time** by automating provisioning and state management using **Terraform** with **S3 backend configuration**.',
      'Cut **deployment time by 50%** and enabled **zero-downtime releases** by integrating test-rich **CI/CD pipelines** using **CircleCI**, **Cypress**, and **Selenium**.',
      'Enabled **reliable real-time communication across distributed services** by building a **RabbitMQ messaging system** over **AMQP**, orchestrating workflows and ensuring durable async message handling.',
    ],
    tech_stack: [
      'JavaScript',
      'TypeScript',
      'React.js',
      'Redux-Saga',
      'MUI',
      'Formik',
      'Yup',
      'Python',
      'Flask',
      'Golang',
      'SQLAlchemy',
      'SQL',
      'REST APIs',
      'Docker',
      'PostgreSQL',
      'Redis',
      'AWS (S3, DynamoDB)',
      'Terraform',
      'NGINX',
      'RabbitMQ',
      'AMQP protocol',
      'CircleCI',
      'Cypress',
      'Selenium',
      'NLP',
      'Algolia',
      'ECharts',
      'Fuse.js',
      'Axios',
      'Moment.js',
      'Lodash',
      'HTML',
      'CSS',
      'JSON',
      'GitHub',
      'SSO',
      'SAML',
      'Agile Methodologies',
      'OOP',
      'CI/CD',
    ],
  },
  {
    title: 'Lead Full Stack Engineer',
    company_name: 'The Nine',
    company_link: 'https://www.nine.is/',
    icon: the_nine_logo,
    iconBg: '#F7F7F7',
    date: 'May 2021 - July 2021',
    points: [
      'Led **end-to-end development** of a logistics recruitment platform used by **500+ trucking companies**, improving **job placement accuracy** and centralizing driver discovery at scale.',
      'Improved **page load speed and responsiveness** by rebuilding the frontend with **React.js**, **Next.js**, and **Node.js**, replacing legacy native code for a modern, scalable UX.',
      'Enhanced **job matching accuracy by 40%** by designing a **filtering engine** that connected **1,000+ users** with optimal logistics roles, streamlining driver-company placement.',
    ],
    tech_stack: [
      'JavaScript',
      'React.js',
      'Redux',
      'Next.js',
      'Node.js',
      'Docker',
      'MongoDB',
      'Mongoose',
      'HTML',
      'CSS',
      'Bootstrap',
    ],
  },
  {
    title: 'Software Engineer Intern',
    company_name: 'Carlin Fit LLC',
    company_link: 'https://fit4friends.com/',
    icon: carlin_fit_llc_logo,
    iconBg: '#F7F7F7',
    date: 'May 2020 - August 2020',
    points: [
      'Improved **user engagement** by rebuilding iOS and Android apps in **Swift** and **Kotlin**, launching **30+ new features** including **real-time progress tracking**, **team challenges**, and **secure authentication flows**.',
      'Increased **user retention and engagement** by building a **multi-user competition engine** with a custom **bidding algorithm** and **PayPal integration** to enable monetized weight loss challenges.',
      'Scaled **backend performance and feature delivery** by upgrading **40+ REST API endpoints**, redesigning the **database schema**, and building **8 Laravel schedulers** to automate background workflows.',
      'Accelerated **cross-platform development** by integrating **React Native components** into the native iOS/Android codebase using **Electrode Native**, ensuring **high performance and maintainability**.',
    ],
    tech_stack: [
      'Kotlin',
      'Java',
      'Swift',
      'React Native',
      'PHP',
      'Laravel',
      'MySQL',
      'AWS',
      'PuTTY',
      'REST APIs',
      'JSON',
      'Bootstrap',
      'Scrum Environment',
      'Android Studio',
      'Xcode',
      'GitHub',
      'Mobile Application Development',
      'PayPal Integration',
      'Electrode Native',
    ],
  },
  {
    title: 'Systems Engineer',
    company_name: 'Infosys',
    company_link: 'https://www.infosys.com/',
    icon: infosys_logo,
    iconBg: '#F7F7F7',
    date: 'January 2019 - May 2019',
    points: [
      'Streamlined **logistics operations** by building a **Venue Management System** on **Oracle E-Business Suite**, improving **supply tracking**, **equipment handling**, and **venue recommendations** for customer-specific needs.',
      'Applied **enterprise tools in production** to support logistics workflows after completing hands-on training in **PL/SQL**, **Oracle EBS Workflow**, **Reports Builder**, and **Python OOP**.',
    ],
    tech_stack: [
      'PL/SQL',
      'SQL',
      'Oracle E-Business Suite',
      'Python',
      'OOP',
      'Oracle EBS Workflow',
      'Oracle Reports Builder',
    ],
  },
];

const testimonials = [
  {
    testimonial:
      "Sai was a 2020 summer graduate intern at Carlin Fit LLC, and was responsible for improving upon our existing mobile application, Fit4Friends, and implementing new features to prepare the app for launch. Sai was genuinely excited by the work and always presented his updates with a high level of enthusiasm and pride, which positively contributed to the overall team moral! And if Sai ever didn't know how to do something, he would take the initiative to research it on his own and learn, which is a great quality to have in a team member! He loved brainstorming user stories, and was never afraid to share his thoughts in team discussions. ",
    name: 'Samantha Carlin',
    designation: 'CEO & Co-Founder',
    connector: 'of',
    company: 'Carlin Fit LLC',
    image: samantha_carlin,
  },
  {
    testimonial:
      "I've had the pleasure of working with Sai on numerous projects, including our time together at Carlin Fit LLC. Sai's technical prowess and problem-solving skills are unparalleled. His ability to seamlessly collaborate and drive projects to successful completion is a testament to his expertise and dedication. Sai is not only a brilliant software engineer but also a supportive teammate who consistently goes above and beyond.",
    name: 'Shreya Nayak',
    designation: 'Software Engineer',
    connector: 'at',
    company: 'UNM Hospitals',
    image: shreya_nayak,
  },
];

const projects = [
  {
    name: 'Patient Management APP',
    description:
      'Engineered a comprehensive healthcare patient management application that streamlines the process for patients to register, book, and manage appointments with doctors. Developed robust administrative tools for scheduling, confirming, and canceling appointments, providing administrators with full control over the appointment lifecycle. Integrated a user-friendly dashboard where patients can easily view, reschedule, or cancel their appointments. Enhanced the application with features such as secure user authentication, responsive UI design, and a sidebar for patients to update their information, schedule new appointments, and manage their profiles, significantly improving the overall user experience.',
    tags: [
      'Next.js',
      'React',
      'ShadCN',
      'TailwindCSS',
      'Typescript',
      'Prisma',
      'PostgreSQL',
      'Zod',
      'JWT',
      'Swiper',
    ],
    images: [user_dashboard, registration_appointment, singup, admin],
    source_code_link: 'https://github.com/saichandras/carepulse',
    variant: 'website',
  },
  {
    name: 'Tracker APP',
    description:
      'Developed a mobile app with real-time tracking and mapping of user paths, implementing polylines on maps to visualize the traversed route, and engineered a secure backend for user authentication, account management, and REST API endpoints to manage and synchronize track data.',
    tags: ['React Native', 'MongoDB', 'Mongoose', 'Express.js', 'Node.js', 'JWT'],
    images: [tracker_1, tracker_2, tracker_3],
    source_code_link: 'https://github.com/saichandras/TrackerApp',
    variant: 'mobile',
  },
  {
    name: 'Meals APP',
    description:
      'Crafted a React Native app with Redux, offering a curated selection of over 50 categorized meal recipes, complete with detailed descriptions and preparation instructions, featuring robust filtering and favoriting capabilities.',
    tags: ['React Native', 'React Redux'],
    images: [meals_1, meals_2, meals_3],
    source_code_link: 'https://github.com/saichandras/MealsApp',
    variant: 'mobile',
  },
  {
    name: 'Blogs APP',
    description:
      'Designed an app in React Native and React Context using JSON API server calls to create, edit, and delete the blogs.',
    tags: ['React Native', 'React Context', 'JSON API'],
    images: [blogs_1, blogs_2, blogs_3],
    source_code_link: 'https://github.com/saichandras/BlogApp',
    variant: 'mobile',
  },
  {
    name: 'Tic Tac Toe',
    description:
      'A classic Tic Tac Toe game built using Android Studio and Kotlin. It allows two players to input their names and play on a single device with a dynamic game board that updates with player moves, ensuring fair play and declaring a winner or a tie.',
    tags: ['Android Studio', 'Kotlin', 'Java'],
    images: [tictactoe],
    source_code_link: 'https://github.com/saichandras/TicTacToe',
    variant: 'mobile',
  },
  {
    name: 'Search Restaurants',
    description:
      'An intuitive app using the Yelp API to find nearby restaurants. It categorizes results based on ratings, cost, and reviews, offering a responsive UI for searching by name or browsing categories, with detailed restaurant information including ratings and images.',
    tags: ['React Native', 'React Redux', "Yelp API's"],
    images: [food_app],
    source_code_link: 'https://github.com/saichandras/RestaurantsApp',
    variant: 'mobile',
  },
  {
    name: 'Target Sum',
    description:
      'A number puzzle game developed with Android Studio and Kotlin. Players select numbers to match a target sum within a time limit, featuring a simple interface, clear instructions, and dynamic gameplay to enhance problem-solving skills and speed.',
    tags: ['React Native', 'React Context'],
    images: [target_sum],
    source_code_link: 'https://github.com/saichandras/TargetSum',
    variant: 'mobile',
  },
];

const social_icons = [
  {
    name: 'LinkedIn',
    icon_path: './linkedin/linkedin1.gltf',
    link: 'https://www.linkedin.com/in/saichandras/',
    args: {
      scale: 2.65,
      position: [0, -3.3, 0],
    },
  },
  {
    name: 'GitHub',
    icon_path: './github/github2.gltf',
    link: 'https://github.com/saichandras',
    args: {
      scale: 0.889,
      position: [0, -0.2, 0],
    },
  },
  {
    name: 'Resume',
    icon_path: './resume/resume1.gltf',
    link: 'https://drive.google.com/file/d/1s6VpI7O_BdBWYc9vHlQvhb1I0-D_uZ2y/view?usp=sharing',
    args: {
      scale: 1.25,
      position: [0, -0.65, 0],
    },
  },
];

export { services, technologies, experiences, testimonials, projects, social_icons };
