name: PR Deploy to Surge

on:
  pull_request:
    branches: ['master']

permissions:
  contents: read
  pull-requests: write

jobs:
  preview:
    environment:
      name: pr-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to Surge
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
        run: |
          npm install -g surge
          surge ./dist --domain ${{ github.sha }}-saichandras.surge.sh

      - name: Post deployment URL as comment
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Preview deployment for this PR: https://${{ github.sha }}-saichandras.surge.sh\n\nTo teardown this deployment, go to the [Actions tab](https://github.com/${{ github.repository }}/actions/workflows/teardown.yml) and select "Run workflow" with the domain "https://${{ github.sha }}-saichandras.surge.sh".`
            })
