name: Teardown Preview Deployment

on:
  workflow_dispatch:
    inputs:
      deploy_dir:
        description: 'Directory to teardown'
        required: true

permissions:
  contents: write

jobs:
  teardown:
    runs-on: ubuntu-latest
    steps:
      - name: Configure git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Clone Preview Repository
        env:
          GH_PREVIEW_TOKEN: ${{ secrets.GH_PREVIEW_TOKEN }}
        run: |
          git clone https://x-access-token:${{ secrets.GH_PREVIEW_TOKEN }}@github.com/saichandras/saichandras-preview.git
          cd saichandras-preview
          git rm -rf ${{ github.event.inputs.deploy_dir }}
          git commit -m "Teardown preview deployment for directory ${{ github.event.inputs.deploy_dir }}"
          git push origin main
