name: Teardown Surge deployment

on:
  pull_request:
    types: [closed]

permissions:
  contents: read
  pull-requests: write

jobs:
  teardown:
    if: github.event.pull_request.merged == true
    environment:
      name: pr-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Teardown Surge deployment
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
        run: |
          npm install -g surge
          surge teardown ${{ github.sha }}-saichandras.surge.sh
