name: Teardown Preview Deployment

on:
  workflow_dispatch:
    inputs:
      directory:
        description: 'Directory to remove'
        required: true

permissions:
  contents: write

jobs:
  teardown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch gh-pages-preview branch
        run: |
          git fetch origin gh-pages-preview:gh-pages-preview
          git checkout gh-pages-preview

      - name: Remove preview directory
        run: |
          DIR_TO_REMOVE=${{ github.event.inputs.directory }}
          rm -rf ${DIR_TO_REMOVE}

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Remove preview directory ${{ github.event.inputs.directory }}"
          git push origin gh-pages-preview
