name: Teardown Surge Deployment

on:
  workflow_dispatch:
    inputs:
      domain:
        description: 'The Surge domain to teardown'
        required: true

permissions:
  contents: read

jobs:
  teardown:
    runs-on: ubuntu-latest
    steps:
      - name: Teardown Surge deployment
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
        run: |
          npm install -g surge
          surge teardown ${{ github.event.inputs.domain }}
