name: Teardown Surge deployment

on:
  push:
    branches:
      - '**'
  pull_request:
    types: [closed, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  teardown:
    if: github.event.pull_request.merged == true || github.event.action == 'synchronize'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Try to download previous SHA
        id: download_sha
        run: |
          echo "Trying to download previous SHA"
          actions/download-artifact@v2 --name commit-sha --path .
          if [ $? -ne 0 ]; then
            echo "exists=false" >> $GITHUB_ENV
          else
            echo "exists=true" >> $GITHUB_ENV
          fi

      - name: Check if SHA file exists
        if: env.exists == 'true'
        id: check_sha
        run: echo "Previous SHA file found."

      - name: Teardown previous Surge deployment
        if: env.exists == 'true'
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
        run: |
          PREVIOUS_SHA=$(cat sha.txt)
          npm install -g surge
          surge teardown $PREVIOUS_SHA-saichandras.surge.sh || echo "No previous deployment found, skipping teardown."

      - name: Teardown current Surge deployment
        if: github.event.pull_request.merged == true
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
        run: |
          npm install -g surge
          surge teardown ${{ github.sha }}-saichandras.surge.sh || echo "No current deployment found, skipping teardown."
